# Generated by Django 4.2.11 on 2026-03-09 10:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sintoma_principal', models.CharField(choices=[('peito', 'Aperto no Peito \U0001fac0'), ('respiracao', 'Dificuldade de Respirar 😤'), ('confusao', 'Confusão Mental 🌀'), ('medo', 'Medo Intenso 😨'), ('outro', 'Outro')], help_text='Qual é seu sintoma principal neste momento?', max_length=50)),
                ('ambiente_seguro', models.BooleanField(default=True, help_text='Você está em um ambiente seguro no momento?')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, help_text='Deixe vazio para registro anônimo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergencias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Emergência Emocional',
                'verbose_name_plural': 'Emergências Emocionais',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['usuario', '-criado_em'], name='suporte_eme_usuario_983024_idx'), models.Index(fields=['sintoma_principal'], name='suporte_eme_sintoma_8c46be_idx'), models.Index(fields=['ambiente_seguro'], name='suporte_eme_ambient_4ee261_idx')],
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clima_interno', models.CharField(choices=[('ensolarado', 'Ensolarado ☀️'), ('nublado', 'Nublado ☁️'), ('tempestuoso', 'Tempestuoso ⛈️'), ('neblina', 'Neblina 🌫️')], help_text='Como está seu estado emocional interno?', max_length=20)),
                ('nivel_ruido', models.IntegerField(help_text='Nível de "ruído mental" (1=silencioso, 10=caótico)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('gatilho', models.CharField(choices=[('trabalho', 'Trabalho'), ('familia', 'Família'), ('telas', 'Telas/Redes Sociais'), ('sono', 'Falta de Sono'), ('saude', 'Saúde Física'), ('relacionamento', 'Relacionamento'), ('financeiro', 'Financeiro'), ('desconhecido', 'Desconhecido'), ('outro', 'Outro')], help_text='Qual foi o gatilho principal do seu estado?', max_length=50)),
                ('auto_eficacia', models.IntegerField(help_text='Nível de confiança em lidar com as emoções (0-10)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Check-in de Prevenção',
                'verbose_name_plural': 'Check-ins de Prevenção',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['usuario', '-criado_em'], name='suporte_che_usuario_eecc87_idx'), models.Index(fields=['clima_interno'], name='suporte_che_clima_i_e19117_idx'), models.Index(fields=['gatilho'], name='suporte_che_gatilho_218c2b_idx')],
            },
        ),
    ]
