# Generated by Django 4.2.11 on 2026-03-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suporte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='notas',
            field=models.TextField(blank=True, help_text='Notas adicionais ou observações sobre o seu estado'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='sintomas',
            field=models.TextField(blank=True, help_text='Descreva os sintomas físicos ou emocionais que está sentindo'),
        ),
    ]
