# Generated by Django 4.2.11 on 2026-03-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suporte', '0004_emergencia_contadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nome_contato_apoio',
            field=models.CharField(blank=True, help_text='Nome da pessoa que deve ser acionada em caso de crise', max_length=120),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vinculo_contato_apoio',
            field=models.CharField(blank=True, help_text='Vínculo com a pessoa de apoio (ex: Mãe, Amigo, Cônjuge)', max_length=80),
        ),
    ]
