# Generated by Django 4.2.11 on 2026-04-01 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suporte', '0005_userprofile_nome_contato_apoio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsicologoProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_profissional', models.CharField(db_index=True, max_length=40, unique=True)),
                ('especialidade', models.CharField(blank=True, max_length=120)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='psicologo_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Psicólogo',
                'verbose_name_plural': 'Perfis de Psicólogo',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nome_psicologo',
            field=models.CharField(blank=True, help_text='Nome do psicólogo informado pelo paciente', max_length=120),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='registro_ordem_psicologo',
            field=models.CharField(blank=True, db_index=True, help_text='Registro profissional do psicólogo (ordem) informado pelo paciente', max_length=40),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telefone_psicologo',
            field=models.CharField(blank=True, help_text='Telefone do psicólogo informado pelo paciente', max_length=20),
        ),
        migrations.CreateModel(
            name='VinculoTerapeutico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vinculo_terapeutico', to=settings.AUTH_USER_MODEL)),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='suporte.psicologoprofile')),
            ],
            options={
                'verbose_name': 'Vínculo Terapêutico',
                'verbose_name_plural': 'Vínculos Terapêuticos',
                'indexes': [models.Index(fields=['psicologo', 'status'], name='suporte_vin_psicolo_cbc9f9_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_clinicas', to=settings.AUTH_USER_MODEL)),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_clinicas', to='suporte.psicologoprofile')),
            ],
            options={
                'verbose_name': 'Nota Clínica',
                'verbose_name_plural': 'Notas Clínicas',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['psicologo', 'paciente', '-criado_em'], name='suporte_not_psicolo_1e0d44_idx')],
            },
        ),
    ]
